import { buildGoModel } from '/lib/go-times.js';
import { uniqueCameraCount } from '/lib/homepage-ranking.js';

(() => {
  const host = document.getElementById('localNow');
  if (!host) return;
  const VARIANT='icon-carousel';
  const MODES=['driving','go','skyway','today'];
  const MODE_SHOW={driving:'Show Driving',go:'Show GO',skyway:'Show Skyway',today:'Show Event'};
  const MODE_CAT={driving:'TRAFFIC',go:'GO',skyway:'SKYWAY',today:'EVENT'};
  const SWIPE_PX=36;
  window.liveUtilityVariant=VARIANT;
  const esc=value=>String(value||'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  let selectedMode=null,lastModels=null,lastPayload=null,viewed=false;
  const icon=(name,path)=>`<span class="now-icon now-icon-${name}" aria-hidden="true"><svg viewBox="0 0 24 24">${path}</svg></span>`;
  const icons={driving:icon('traffic','<path d="M5 16h14l-1.2-6.2A2 2 0 0 0 15.9 8H8.1a2 2 0 0 0-1.9 1.8L5 16Z"/><path d="M7 16v2M17 16v2M8 11h8"/>'),go:icon('go','<rect x="6" y="4" width="12" height="16" rx="3"/><path d="M9 8h6M9 12h6M10 18h4"/>'),skyway:icon('skyway','<path d="M3 16h18M5 16c2-6 5-9 7-9s5 3 7 9"/><path d="M8 16v-3M16 16v-3"/>'),today:icon('event','<rect x="4" y="5" width="16" height="16" rx="2"/><path d="M8 3v4M16 3v4M4 11h16"/>')};
  function track(name,mode){try{window.dataLayer=window.dataLayer||[];window.dataLayer.push({event:name,liveUtilityVariant:VARIANT,mode:mode||selectedMode||'driving'})}catch(_){}}
  function drivingModel(surface,intel){const incident=(surface?.incidents||[]).find(x=>/burlington|oakville|halton|qew|403|skyway/i.test(`${x.municipality||''} ${x.roadway||''} ${x.title||''}`));if(incident)return{title:(incident.roadway||'QEW')+' traffic',metric:/closed/i.test(incident.title||'')?'Closed':'Live',detail:incident.title||'',url:'/traffic/',alert:true};const route=surface?.routes?.toronto;return{title:'QEW → Toronto',metric:route?.status?.looks||'Live',detail:'Live cameras and incidents',url:'/traffic/?destination=toronto'};}
  function goModel(data){const model=buildGoModel(data||{},new Date());return{title:'Burlington → Union',time:model?.time||'',status:model?.status||'',detail:model?.detail||'',url:'/go/burlington-to-union/',alert:!!model?.alert};}
  function skywayModel(surface){const route=surface?.routes?.hamilton||surface?.routes?.toronto;const cameras=uniqueCameraCount(route?.cameras||[]);return{title:'Burlington Skyway',metric:cameras?`${cameras} cameras`:'Live',detail:'Check current bridge traffic',url:'/traffic/?focus=skyway'};}
  function todayModel(explore){const item=(explore?.items||explore?.events||[])[0];return item?{title:item.title||item.name,relative:item.relative||'',hours:item.hours||'',url:item.url||'/explore/'}:null;}
  function compactCard(mode,model){if(mode==='today'&&!model)model={title:'What’s on in Burlington',url:'/explore/'};const title=model.title||model.headline;const metric=mode==='go'?(model.time||''):(mode==='today'?(model.relative||''):(model.metric||''));const detail=mode==='go'?[model.status,model.detail].filter(Boolean).join(' · '):(mode==='today'?(model.hours||''):(model.extra||model.detail||''));return `<div class="now-card-shell"><a class="now-card now-card-${mode}${model.alert?' is-alert':''}" href="${esc(model.url||'#')}" data-utility-card="${mode}">${icons[mode]}<span class="now-card-copy"><small class="now-card-cat">${MODE_CAT[mode]}</small><strong>${esc(title)}</strong>${detail?`<em>${esc(detail)}</em>`:''}</span>${metric?`<b class="now-card-metric">${esc(metric)}</b>`:''}</a></div>`;}
  function cardFor(mode){return compactCard(mode,lastModels[mode]);}
  function applyMode(mode){if(!lastModels||!MODES.includes(mode))return;selectedMode=mode;host.querySelectorAll('[data-now-dot]').forEach(tab=>{const on=tab.dataset.mode===mode;tab.classList.toggle('is-active',on);tab.setAttribute('aria-selected',String(on));tab.setAttribute('aria-current',on?'true':'false')});const panel=host.querySelector('[role="tabpanel"]');if(panel){panel.innerHTML=cardFor(mode);bindCard(panel)}}
  function stepMode(delta){const i=MODES.indexOf(selectedMode);applyMode(MODES[(i+delta+MODES.length)%MODES.length]);track('live_utility_mode_change',selectedMode)}
  function bindCard(panel){const card=panel?.querySelector('[data-utility-card]');if(!card)return;let sx=0,sy=0,swiping=false;card.addEventListener('touchstart',e=>{sx=e.touches[0].clientX;sy=e.touches[0].clientY;swiping=false},{passive:true});card.addEventListener('touchmove',e=>{const dx=e.touches[0].clientX-sx,dy=e.touches[0].clientY-sy;if(Math.abs(dx)>10&&Math.abs(dx)>Math.abs(dy)){swiping=true;if(e.cancelable)e.preventDefault()}},{passive:false});card.addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-sx;if(swiping&&Math.abs(dx)>=SWIPE_PX)stepMode(dx<0?1:-1)});card.addEventListener('click',e=>{if(swiping){e.preventDefault();return}track('live_utility_card_click',selectedMode)});}
  function render(payload){lastPayload=payload;lastModels={driving:drivingModel(payload.surface,payload.intel),go:goModel(payload.go),skyway:skywayModel(payload.surface),today:todayModel(payload.explore)};selectedMode=selectedMode||'driving';host.innerHTML=`<div class="now-panel" role="tabpanel">${cardFor(selectedMode)}</div><div class="now-dots" role="tablist" aria-label="Live local update">${MODES.map(mode=>`<button type="button" class="now-dot-btn${mode===selectedMode?' is-active':''}" role="tab" data-now-dot data-mode="${mode}" aria-label="${MODE_SHOW[mode]}" aria-selected="${mode===selectedMode}" aria-current="${mode===selectedMode?'true':'false'}"><span class="now-pager-dot" aria-hidden="true"></span></button>`).join('')}</div>`;host.querySelectorAll('[data-now-dot]').forEach(tab=>tab.addEventListener('click',()=>applyMode(tab.dataset.mode)));bindCard(host.querySelector('[role="tabpanel"]'));if(!viewed){viewed=true;track('live_utility_view',selectedMode)}}
  function load(){Promise.allSettled([fetch('/data/traffic-surface.json',{cache:'no-store'}).then(r=>r.ok?r.json():null),fetch('/data/go-status.json',{cache:'no-store'}).then(r=>r.ok?r.json():null),fetch('/data/local-intelligence.json',{cache:'no-store'}).then(r=>r.ok?r.json():null),fetch('/data/explore-events.json',{cache:'no-store'}).then(r=>r.ok?r.json():null)]).then(r=>render({surface:r[0].value,go:r[1].value,intel:r[2].value,explore:r[3].value})).catch(()=>{host.hidden=true})}
  load();setInterval(load,120000);
})();
