(() => {
  const host = document.getElementById('localNow');
  if (!host) return;
  const esc = value => String(value || '').replace(/[&<>"']/g, character => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[character]));
  const relative = value => { const date=new Date(value); if(!Number.isFinite(date.getTime()))return'recently'; const minutes=Math.max(0,Math.round((Date.now()-date.getTime())/60000)); if(minutes<2)return'1 min ago'; if(minutes<60)return`${minutes} min ago`; const hours=Math.round(minutes/60); return hours<24?`${hours} hr ago`:new Intl.DateTimeFormat('en-CA',{month:'short',day:'numeric'}).format(date); };
  const isFresh=(value,maxMinutes=90)=>{const date=new Date(value);return Number.isFinite(date.getTime())&&Date.now()-date.getTime()<=maxMinutes*60000};
  const timeOnly=value=>{if(!value)return'';const raw=String(value);const match=raw.match(/(\d{1,2}):(\d{2})/);if(!match)return raw;let hour=Number(match[1]);const minute=match[2];const suffix=hour>=12?'pm':'am';hour=hour%12||12;return`${hour}:${minute} ${suffix}`};
  function cachedSkyway(){try{const saved=JSON.parse(localStorage.getItem('burlington-skyway-traffic')||'null');if(saved&&saved.label&&isFresh(saved.updatedAt,20))return saved.label}catch(_){}return''}
  function goSummary(data){
    if(!data||!isFresh(data.generatedAt,90))return{label:'GO',value:'Times unavailable',url:'https://www.gotransit.com/en/see-schedules'};
    const alert=Array.isArray(data.alerts)&&data.alerts[0];
    if(alert)return{label:'GO',value:alert.headline||'Service alert',url:data.liveStatusUrl||'https://www.gotransit.com/en/see-schedules',alert:true};
    const routes=Array.isArray(data.routes)?data.routes:[];
    const departures=[];
    routes.forEach(route=>{
      const first=Array.isArray(route.journeys)?route.journeys[0]:null;
      if(!first)return;
      const destination=route.destination?.label||'';
      const departure=timeOnly(first.computedDeparture||first.departure);
      if(destination&&departure)departures.push(`${destination} ${departure}`);
    });
    if(departures.length)return{label:'GO',value:departures.slice(0,2).join(' · '),url:data.liveStatusUrl||'https://www.gotransit.com/en/see-schedules'};
    return{label:'GO',value:data.dataKind==='realtime'?'On time':'Scheduled',url:data.liveStatusUrl||'https://www.gotransit.com/en/see-schedules'};
  }
  function cameraEstimate(){return new Promise(resolve=>{const image=new Image();let done=false;const finish=v=>{if(done)return;done=true;resolve(v)};const timer=setTimeout(()=>finish(''),3500);image.onload=()=>{clearTimeout(timer);try{const canvas=document.createElement('canvas');canvas.width=160;canvas.height=90;const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(image,0,0,160,90);const data=ctx.getImageData(0,25,160,65).data;let edges=0,samples=0,prev=null;for(let i=0;i<data.length;i+=16){const lum=.2126*data[i]+.7152*data[i+1]+.0722*data[i+2];if(prev!==null&&Math.abs(lum-prev)>34)edges++;prev=lum;samples++}const avg=samples?edges/samples:0;const label=avg>.34?'heavy':avg>.25?'moderate':'light';try{localStorage.setItem('burlington-skyway-traffic',JSON.stringify({label,updatedAt:new Date().toISOString()}))}catch(_){}finish(label)}catch(_){finish('')}};image.onerror=()=>{clearTimeout(timer);finish('')};image.src=`https://511on.ca/map/Cctv/10?t=${Date.now()}`})}
  async function skywaySummary(){const cached=cachedSkyway();if(cached)return{label:'Skyway',value:cached[0].toUpperCase()+cached.slice(1),url:'skyway-traffic.html'};const visual=await cameraEstimate();if(visual)return{label:'Skyway',value:visual[0].toUpperCase()+visual.slice(1),url:'skyway-traffic.html'};try{const response=await fetch('https://511on.ca/api/v2/get/event?format=json&lang=en',{cache:'no-store'});if(!response.ok)throw new Error();const events=await response.json();const nearby=(Array.isArray(events)?events:[]).filter(event=>{const text=`${event.RoadwayName||''} ${event.EventType||''} ${event.EventSubType||''} ${event.Description||''}`.toLowerCase();return/qew|skyway|burlington/.test(text)&&/collision|accident|closure|blocked|lane/.test(text)});return nearby.length?{label:'Skyway',value:'Incident',url:'skyway-traffic.html',alert:true}:{label:'Skyway',value:'Clear',url:'skyway-traffic.html'}}catch(_){return{label:'Skyway',value:'Live cameras',url:'skyway-traffic.html'}}}
  Promise.allSettled([fetch('data/local-status.json',{cache:'no-store'}).then(response=>response.ok?response.json():Promise.reject()),fetch('data/go-status.json',{cache:'no-store'}).then(response=>response.ok?response.json():null).catch(()=>null),skywaySummary()]).then(results=>{if(results[0].status!=='fulfilled'){host.hidden=true;return}const data=results[0].value;const go=results[1].status==='fulfilled'?results[1].value:null;const skyway=results[2].status==='fulfilled'?results[2].value:{label:'Skyway',value:'Live cameras',url:'skyway-traffic.html'};const incidents=Array.isArray(data.incidents)?data.incidents:[];const recent=Array.isArray(data.recentlyLive)?data.recentlyLive:[];const current=incidents[0];const goItem=goSummary(go);const incidentMarkup=current?`<a class="now-priority" href="${esc(current.url||'updates.html')}"><span><small>${esc(current.status||'Local alert')}</small><strong>${esc(current.headline)}</strong><em>${esc(current.location?.label||current.impact||'')}</em></span><time>${esc(relative(current.lastUpdatedAt||data.generatedAt))}</time></a>`:'';const recentMarkup=!current&&recent.length?`<a class="now-priority is-recent" href="${esc(recent[0].url||'updates.html')}"><span><small>Earlier today</small><strong>${esc(recent[0].headline)}</strong><em>${esc(recent[0].location?.label||recent[0].status||'')}</em></span><time>${esc(relative(recent[0].resolvedAt||recent[0].lastUpdatedAt||data.generatedAt))}</time></a>`:'';host.innerHTML=`<div class="now-heading"><span><i class="live-pulse" aria-hidden="true"></i>Right now</span><time>Updated ${esc(relative(data.generatedAt))}</time></div>${incidentMarkup||recentMarkup}<div class="now-inline"><span class="now-inline-item"><small>Weather</small><strong data-weather-temperature>--</strong></span><a class="now-inline-item${skyway.alert?' is-alert':''}" href="${esc(skyway.url)}"><small>${esc(skyway.label)}</small><strong>${esc(skyway.value)}</strong></a><a class="now-inline-item${goItem.alert?' is-alert':''}" href="${esc(goItem.url)}" target="_blank" rel="noopener"><small>${esc(goItem.label)}</small><strong>${esc(goItem.value)}</strong></a><a class="now-inline-item" href="explore.html"><small>This week</small><strong>Events</strong></a></div>`;if(window.BurlingtonWeather?.load)window.BurlingtonWeather.load()}).catch(()=>{host.hidden=true});
})();
