(() => {
  const host=document.getElementById('localNow');if(!host)return;
  const esc=value=>String(value||'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const relative=value=>{const date=new Date(value);if(!Number.isFinite(date.getTime()))return'recently';const minutes=Math.max(0,Math.round((Date.now()-date.getTime())/60000));if(minutes<2)return'1 min ago';if(minutes<60)return`${minutes} min ago`;const hours=Math.round(minutes/60);return hours<24?`${hours} hr ago`:new Intl.DateTimeFormat('en-CA',{month:'short',day:'numeric'}).format(date)};
  const isFresh=(value,maxMinutes=180)=>{const date=new Date(value);return Number.isFinite(date.getTime())&&Date.now()-date.getTime()<=maxMinutes*60000};
  const timeOnly=value=>{if(!value)return'';const raw=String(value);const match=raw.match(/(\d{1,2}):(\d{2})/);if(!match)return raw;let hour=Number(match[1]);const minute=match[2];const suffix=hour>=12?'pm':'am';hour=hour%12||12;return`${hour}:${minute} ${suffix}`};
  const torontoDate=()=>{try{return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Toronto',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}catch(_){return new Date().toISOString().slice(0,10)}};
  const goTripUrl=destination=>`https://www.gotransit.com/en/see-schedules?tripPoint=7700&departure=BU&destination=${encodeURIComponent(destination)}&date=${encodeURIComponent(torontoDate())}&transfers=true`;
  function goSummary(data,destinationCode,destinationLabel){const route=(Array.isArray(data?.routes)?data.routes:[]).find(item=>String(item.destination?.stopCode||'').toUpperCase()===destinationCode);const journeys=Array.isArray(route?.journeys)?route.journeys:[];const times=journeys.slice(0,2).map(j=>timeOnly(j.computedDeparture||j.departure)).filter(Boolean);const url=goTripUrl(destinationCode);if(times.length)return{label:`GO → ${destinationLabel}`,value:times.join(' · '),url,stale:!isFresh(data?.generatedAt,180)};return{label:`GO → ${destinationLabel}`,value:'Check times',url}}
  function goAlert(data){const alert=Array.isArray(data?.alerts)&&data.alerts[0];return alert?{headline:alert.headline||'GO service alert',url:data.liveStatusUrl||'https://www.gotransit.com/en/service-updates/service-updates'}:null}
  function intelligenceSummary(data){const top=data?.topSignal;if(!top||!isFresh(data.generatedAt,120))return null;return{headline:top.headline,status:top.kind==='transit'?'Transit alert':'Traffic alert',location:top.location||top.neighbourhood||'Burlington',url:top.url||'updates.html',lastUpdatedAt:data.generatedAt,score:Number(top.score)||0}}
  function skywaySummary(data){const incidents=Array.isArray(data?.traffic?.incidents)?data.traffic.incidents:[];const major=incidents.find(item=>(Number(item.score)||0)>=60);if(major)return{label:'Skyway traffic',value:'Incident',url:'skyway-traffic.html',alert:true};return{label:'Skyway traffic',value:incidents.length?'Watch':'Clear',url:'skyway-traffic.html'}}
  function transitSummary(data){const alerts=Array.isArray(data?.transit?.alerts)?data.transit.alerts:[];if(alerts.length)return{label:'Burlington Transit',value:'Service alert',url:alerts[0].url||'https://www.burlington.ca/en/transit/service-alerts.aspx',alert:true};const vehicles=Number(data?.transit?.vehicleCount)||0;return{label:'Burlington Transit',value:vehicles?`${vehicles} buses live`:'Live status',url:'https://www.burlington.ca/en/transit/transit.aspx'}}
  Promise.allSettled([
    fetch('data/local-status.json',{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject()),
    fetch('data/go-status.json',{cache:'no-store'}).then(r=>r.ok?r.json():null).catch(()=>null),
    fetch('data/local-intelligence.json',{cache:'no-store'}).then(r=>r.ok?r.json():null).catch(()=>null)
  ]).then(results=>{if(results[0].status!=='fulfilled'){host.hidden=true;return}const data=results[0].value;const go=results[1].status==='fulfilled'?results[1].value:null;const intel=results[2].status==='fulfilled'?results[2].value:null;const incidents=Array.isArray(data.incidents)?data.incidents:[];const recent=Array.isArray(data.recentlyLive)?data.recentlyLive:[];const editorial=incidents[0]||recent[0]||null;const live=intelligenceSummary(intel);const goServiceAlert=goAlert(go);const alertPriority=goServiceAlert?{headline:goServiceAlert.headline,status:'GO alert',location:'Lakeshore West',url:goServiceAlert.url,lastUpdatedAt:go?.generatedAt,score:75}:null;const machinePriority=[live,alertPriority].filter(Boolean).sort((a,b)=>(b.score||0)-(a.score||0))[0]||null;const priority=machinePriority&&(!editorial||machinePriority.score>=65)?machinePriority:editorial;const union=goSummary(go,'UN','Union');const westHarbour=goSummary(go,'WR','West Harbour');const skyway=skywaySummary(intel);const transit=transitSummary(intel);const generatedAt=intel?.generatedAt||go?.generatedAt||data.generatedAt;const isCurrent=priority===machinePriority||incidents.includes(priority);const priorityMarkup=priority?`<a class="now-priority${isCurrent?'':' is-recent'}" href="${esc(priority.url||'updates.html')}"><span><small>${esc(isCurrent?(priority.status||'Local update'):'Earlier today')}</small><strong>${esc(priority.headline)}</strong><em>${esc(priority.location?.label||priority.location||priority.impact||priority.status||'')}</em></span><time>${esc(relative(priority.lastUpdatedAt||priority.resolvedAt||generatedAt))}</time></a>`:'';host.innerHTML=`<div class="now-heading"><span><i class="live-pulse" aria-hidden="true"></i>Right now</span><time>Updated ${esc(relative(generatedAt))}</time></div>${priorityMarkup}<div class="now-inline"><span class="now-inline-item"><small>Weather</small><strong data-weather-temperature>--</strong></span><a class="now-inline-item${skyway.alert?' is-alert':''}" href="${esc(skyway.url)}"><small>${esc(skyway.label)}</small><strong>${esc(skyway.value)}</strong></a><a class="now-inline-item" href="${esc(union.url)}" target="_blank" rel="noopener"><small>${esc(union.label)}</small><strong>${esc(union.value)}</strong></a><a class="now-inline-item" href="${esc(westHarbour.url)}" target="_blank" rel="noopener"><small>${esc(westHarbour.label)}</small><strong>${esc(westHarbour.value)}</strong></a><a class="now-inline-item${transit.alert?' is-alert':''}" href="${esc(transit.url)}" target="_blank" rel="noopener"><small>${esc(transit.label)}</small><strong>${esc(transit.value)}</strong></a><a class="now-inline-item" href="explore.html"><small>This week</small><strong>Events</strong></a></div>`;if(window.BurlingtonWeather?.load)window.BurlingtonWeather.load()}).catch(()=>{host.hidden=true});
})();
