(() => {
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const home=()=>location.pathname==='/'||location.pathname.endsWith('/index.html');
  const dateText=()=>new Intl.DateTimeFormat('en-CA',{weekday:'long',month:'long',day:'numeric',year:'numeric'}).format(new Date());
  const evidenceLabel=item=>{
    const status=String(item.status||'').toLowerCase(),score=Number(item.evidenceScore||0);
    if(/personal experience|assessment|opinion/.test(status))return['Personal experience','evidence-opinion'];
    if(/unsupported|not verified|no reliable/.test(status)||score===0)return['Not verified','evidence-unverified'];
    if(/partly|incomplete|motive/.test(status)||score===1||score===2)return['Partly verified','evidence-partly'];
    return['Verified','evidence-verified'];
  };

  async function stories(){
    try{const r=await fetch('data/source-monitor.json',{cache:'no-store'}),d=await r.json();return (d.items||[]).map(x=>({...x,headline:x.headline||x.title||'',summary:x.summary||x.description||''})).filter(x=>{const words=x.headline.trim().split(/\s+/);return x.url&&words.length>=6&&words.length<=20&&x.summary.length>=45&&!/^(List of Candidates|For Candidates|Candidate Financials|Candidate News and Updates|Infrastructure and Growth|Low Water.*)$/i.test(x.headline)&&x.summary.toLowerCase()!==x.headline.toLowerCase()&&!/(\b\w+\b)(?:\s+\1){2,}/i.test(x.headline)}).slice(0,3)}catch(_){return[]}
  }
  const media=item=>item?.image?`<img src="${esc(item.image)}" alt="" loading="eager">`:'<span class="publication-media-mark" aria-hidden="true">B</span>';
  async function buildPublicationHome(){
    if(!home()||document.querySelector('.publication-home'))return;
    const main=document.getElementById('main'),items=await stories();if(!main)return;
    const fallback=[
      {tag:'Election',headline:'A clear guide to Burlington’s 2026 election',summary:'Compare candidates, understand the jobs and see the dates that matter.',url:'#election-guide'},
      {tag:'Your ballot',headline:'See every race on your Burlington ballot',summary:'Choose your ward, then review mayor, councillor and trustee candidates.',url:'ballot.html'},
      {tag:'Explainer',headline:'Municipal elections, explained from zero',summary:'What council controls, who you elect and how a decision becomes real.',url:'elections-for-beginners.html'}
    ];
    const lead=items.find(x=>x.image&&/burlington|burloak|transit/i.test(`${x.tag||''} ${x.headline||''}`))||items.find(x=>x.image)||items[0]||fallback[0];
    const side=[
      {tag:'Wildlife',headline:'Why Burlington closes a road for salamanders',summary:'The annual King Road closure protects endangered Jefferson salamanders during their spring migration.',url:'https://www.burlington.ca/en/news/burlington-protecting-endangered-salamanders-by-closing-king-road.aspx',image:'https://static.inaturalist.org/photos/24040203/large.jpeg'},
      {tag:'Bird migration',headline:'The birds passing Burlington that most people never notice',summary:'RBG’s long-running monitoring tracks migratory birds moving through the western Lake Ontario area.',url:'https://www.rbg.ca/app/uploads/Long-Watch-Birds-2015-2024-Summary-Report.pdf?x51525=',image:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Cerulean%20Warbler,%20Rondeau%20Provincial%20Park,%20Ontario,%20Canada.jpg?width=900'},
      {tag:'Fish',headline:'More than 26,000 fish passed through one local fishway',summary:'RBG’s 2025 count shows what is migrating into Cootes Paradise and which native species are recovering.',url:'https://www.rbg.ca/2025-cootes-paradise-fishway-highlights-fish-and-fish-migration/',image:'https://rbg-1c124.kxcdn.com/app/uploads/DSC03362-scaled.jpg?x51525'}
    ];
    const section=document.createElement('section');section.className='publication-home';section.innerHTML=`
      <div class="publication-dateline"><span>${esc(dateText())}</span><span>Burlington, Ontario</span></div>
      <div class="publication-heading"><h1>Burlington, in one place.</h1><p>Local news, things to do, civic decisions and an election guide that tells you exactly what each choice means.</p></div>
      <div class="publication-lead-grid"><a class="publication-lead" href="${esc(lead.url)}"><div class="publication-lead-media">${media(lead)}</div><span class="publication-tag">${esc(lead.tag||'Burlington')}</span><h2>${esc(lead.headline)}</h2><p>${esc(lead.summary||lead.description||'Open the full update.')}</p></a><div class="publication-side">${side.map(x=>`<a class="publication-side-story" href="${esc(x.url)}" target="_blank" rel="noopener"><div class="publication-side-media">${media(x)}</div><div class="publication-side-copy"><span class="publication-tag">${esc(x.tag||'Burlington')}</span><h3>${esc(x.headline)}</h3><p>${esc(x.summary||x.description||'Open the full update.')}</p></div></a>`).join('')}</div></div>
      <p class="publication-credit">Wildlife images: Jefferson salamander by Jake Scott, CC BY-SA 3.0; Cerulean warbler by Mdf/MPF, CC BY-SA 3.0; Fishway photo via Royal Botanical Gardens.</p>
      <nav class="publication-shortcuts" aria-label="Popular Burlington sections"><a href="updates.html"><small>Newest</small><strong>Today in Burlington</strong></a><a href="explore.html"><small>Do something</small><strong>Explore Burlington</strong></a><a href="#election-guide"><small>2026 vote</small><strong>Election guide</strong></a><a href="puzzles.html"><small>Play</small><strong>Local puzzles</strong></a></nav>`;
    main.prepend(section);
    const hero=document.querySelector('.election-hero');if(hero)hero.id='election-guide';
    const candidates=document.getElementById('candidates');if(candidates&&!document.querySelector('.explore-teaser')){const e=document.createElement('section');e.className='explore-teaser';e.innerHTML='<div><span class="publication-tag">Shuffle your city</span><h2>Find something in Burlington you would never search for.</h2><p>Local oddities, free stops, overlooked history and small challenges. Start with one card and see where it takes you.</p><a href="explore.html">Shuffle the deck →</a></div><div class="explore-stack" aria-hidden="true"><div class="explore-stack-card"></div><div class="explore-stack-card"></div><div class="explore-stack-card"><small>Try this</small><strong>Find the plaque most people walk past.</strong></div></div>';candidates.insertAdjacentElement('beforebegin',e)}
  }
  function fixEvidence(){
    document.querySelectorAll('.community-quote,.ward-community-card').forEach(card=>{const score=card.querySelector('.community-score,.ward-community-score'),status=card.querySelector('.community-status,.ward-community-status');if(!score||score.dataset.fixed)return;const item={status:status?.textContent||'',evidenceScore:Number((score.textContent.match(/\d+/)||[0])[0])},[label,cls]=evidenceLabel(item);score.textContent=label;score.classList.add(cls);score.dataset.fixed='1'});
  }
  function fixCompare(){const head=document.querySelector('main>.head');if(!head||head.dataset.fixed)return;head.dataset.fixed='1';head.className='compare-intro';head.innerHTML='<h1>Settle the debate in seconds.</h1><p>Choose two mayoral candidates and one issue. You’ll see what each person proposes, the shared facts behind the issue and what still needs checking.</p><div class="compare-how"><div><b>1 · Pick two people</b><span>Change either candidate at any time.</span></div><div><b>2 · Choose an issue</b><span>Taxes, housing, traffic and more.</span></div><div><b>3 · Read the difference</b><span>Promises stay separate from verified records.</span></div></div>'}
  function fixBallot(){document.querySelectorAll('.ballot-school-mini b').forEach(label=>{if(/optional ballot detail/i.test(label.textContent))label.textContent='Your trustee race'});document.querySelectorAll('.ward-candidate-card').forEach(card=>{if(card.querySelector('.ward-incumbent'))return;const name=card.dataset.name;if(['Kelvin Galbraith','Paul Sharman','Angelo Bentivegna'].includes(name)){const body=card.querySelector('.ward-candidate-body'),tag=document.createElement('span');tag.className='ward-incumbent';tag.textContent='Current councillor';body?.insertBefore(tag,body.querySelector('.ward-focus-label'))}})}
  function fixPuzzles(){const main=document.querySelector('.puzzles-main');if(!main||main.dataset.copyFixed)return;main.dataset.copyFixed='1';const h=main.querySelector('h1'),lead=main.querySelector('.puzzles-lead');if(h)h.textContent='Puzzles about Burlington.';if(lead)lead.textContent='Visual questions about local places, history and how the city works.';main.querySelectorAll('.section-rule small').forEach(s=>{if(/quick local games/i.test(s.textContent))s.textContent='Popular puzzles'});main.querySelectorAll('.pick-copy h3').forEach(h3=>{if(/how well do you know burlington/i.test(h3.textContent))h3.textContent='Where in Burlington?'})}
  function fixDates(){const section=document.getElementById('dates'),grid=section?.querySelector('.date-grid');if(!section||!grid)return;let detail=section.querySelector('.date-event-detail');if(!detail){detail=document.createElement('article');detail.className='date-event-detail';detail.id='date-event-detail';detail.innerHTML='<span class="date-detail-kicker">Event details</span><h3>Select a date above</h3><p>The full date and time will appear here.</p>';grid.insertAdjacentElement('afterend',detail)}grid.querySelectorAll('.date-stop,.date-card').forEach(card=>{if(card.dataset.detailBound)return;card.dataset.detailBound='1';card.addEventListener('click',e=>{e.preventDefault();const date=card.querySelector('.date-calendar-day,.date')?.textContent?.trim()||'',month=card.querySelector('.date-calendar-month')?.textContent?.trim()||'',title=card.querySelector('h3')?.textContent?.trim()||'Election event',copy=card.querySelector('p')?.textContent?.trim()||'';detail.innerHTML=`<span class="date-detail-kicker">${esc([month,date].filter(Boolean).join(' '))}</span><h3>${esc(title)}</h3><p>${esc(copy)}</p>`;detail.scrollIntoView({behavior:'smooth',block:'center'})})})}
  function tidyFooter(){document.querySelectorAll('.site-legal-links').forEach(nav=>{if(!nav.querySelector('a[href="promises.html"]'))nav.insertAdjacentHTML('afterbegin','<a href="promises.html">Promises & records</a><a href="explore.html">Explore Burlington</a>')})}
  async function enhancePromises(){const shell=document.querySelector('.record-shell'),toolbar=document.querySelector('.record-toolbar');if(!shell||!toolbar||document.querySelector('.polimeter-summary')||shell.dataset.summaryLoading)return;shell.dataset.summaryLoading='1';try{const data=await fetch('data/track-record.json',{cache:'no-store'}).then(r=>r.json()),wrap=document.createElement('section');wrap.className='polimeter-summary';wrap.innerHTML=Object.entries(data.candidates||{}).map(([name,p])=>{const counts={kept:0,progress:0,partial:0,broken:0,other:0};(p.items||[]).forEach(i=>{const s=String(i.status||'').toLowerCase();if(s==='kept')counts.kept++;else if(/advanced|progress/.test(s))counts.progress++;else if(/partial/.test(s))counts.partial++;else if(/broken|not kept/.test(s))counts.broken++;else counts.other++});const total=p.items.length||1,bar=Object.entries(counts).filter(([,n])=>n).map(([k,n])=>`<span class="bar-${k}" style="width:${n/total*100}%"></span>`).join('');return `<article class="promise-overview"><div class="promise-overview-top"><div><span class="promise-place">Burlington · In office</span><small>Current Ward 2 councillor</small><h2>${esc(name)}</h2></div><span class="promise-see">Reviewed record</span></div><div class="promise-metrics"><div><small>Promises tracked</small><strong>${p.items.length}</strong></div><div><small>Last review</small><strong>${esc(data.updated)}</strong></div><div><small>Overall score</small><strong>Not published</strong></div></div><div class="promise-bar" aria-label="Reviewed promise statuses">${bar}</div><div class="promise-legend"><span><i class="bar-kept"></i>Kept ${counts.kept}</span><span><i class="bar-progress"></i>In progress ${counts.progress}</span>${counts.partial?`<span><i class="bar-partial"></i>Partly kept ${counts.partial}</span>`:''}${counts.broken?`<span><i class="bar-broken"></i>Broken ${counts.broken}</span>`:''}</div><p class="promise-sample-note">This describes the ${p.items.length} commitments reviewed so far. It is not a complete record or a candidate grade.</p></article>`}).join('');toolbar.before(wrap)}catch(_){}finally{shell.dataset.summaryLoading=''}}
  function run(){fixCompare();fixBallot();fixEvidence();fixPuzzles();fixDates();tidyFooter();enhancePromises()}
  document.addEventListener('DOMContentLoaded',()=>{buildPublicationHome();run();const body=document.body;if(body)new MutationObserver(()=>run()).observe(body,{childList:true,subtree:true})},{once:true});
})();
