(() => {
  const root=document.documentElement;
  const storageKey='burlington-news-theme';
  const isHome=()=>location.pathname==='/'||location.pathname.endsWith('/index.html');
  const homeLink=hash=>isHome()?hash:`index.html${hash}`;

  function preferredTheme(){
    try{const saved=localStorage.getItem(storageKey)||localStorage.getItem('burlington-election-theme');if(saved==='light'||saved==='dark')return saved}catch(_){}
    return window.matchMedia?.('(prefers-color-scheme: dark)').matches?'dark':'light';
  }
  function themeIcon(theme){return theme==='dark'?'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M21 12.8A8.7 8.7 0 1 1 11.2 3a7 7 0 0 0 9.8 9.8Z" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/></svg>':'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="4" fill="none" stroke="currentColor" stroke-width="1.8"/><path d="M12 2v2M12 20v2M4.93 4.93l1.41 1.41M17.66 17.66l1.41 1.41M2 12h2M20 12h2M4.93 19.07l1.41-1.41M17.66 6.34l1.41-1.41" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/></svg>'}
  function setTheme(theme,persist=true){
    const next=theme==='dark'?'dark':'light';root.dataset.theme=next;root.style.colorScheme=next;
    document.querySelectorAll('[data-theme-toggle]').forEach(button=>{const target=next==='dark'?'Light mode':'Dark mode';button.innerHTML=`<span class="menu-support-icon">${themeIcon(next)}</span><span>${target}</span>`;button.setAttribute('aria-label',`Switch to ${target.toLowerCase()}`)});
    if(persist)try{localStorage.setItem(storageKey,next)}catch(_){}
  }
  function ensureStyle(href,key){if(document.querySelector(`link[data-style="${key}"]`))return;const l=document.createElement('link');l.rel='stylesheet';l.href=href;l.dataset.style=key;document.head.appendChild(l)}
  function ensureScript(src,key){if(document.querySelector(`script[data-feature="${key}"]`))return;const s=document.createElement('script');s.src=src;s.async=false;s.dataset.feature=key;document.head.appendChild(s)}
  function ensureStyles(){
    ensureStyle('dates-extra.css?v=20260824a','dates');ensureStyle('header-controls.css?v=20260824a','header');ensureStyle('polish-v2.css?v=20260824a','polish');ensureStyle('candidate-cleanup.css?v=20260824a','candidate-cleanup');ensureStyle('branding-v3.css?v=20260824a','branding');ensureStyle('ux-v4.css?v=20260824a','ux-v4');ensureStyle('ux-v5.css?v=20260824a','ux-v5');ensureStyle('ux-v6.css?v=20260824a','ux-v6');ensureStyle('news-v2.css?v=20260824b','news-v2');
  }
  function ensureBanner(){
    let banner=document.querySelector('.banner');const header=document.querySelector('.header');
    if(!banner&&header){banner=document.createElement('div');banner.className='banner';header.before(banner)}
    if(banner)banner.innerHTML='<div class="wrap"><strong>2026 Election Guide</strong>&nbsp;&nbsp;·&nbsp;&nbsp;Voting starts Oct. 14&nbsp;&nbsp;·&nbsp;&nbsp;Election Day Oct. 26</div>';
  }
  function brandMarkup(){return '<span class="news-brand-mark" aria-hidden="true"></span><span class="news-brand-copy"><strong>Burlington News</strong><small>Election Guide</small></span>'}
  function applyBrand(){document.querySelectorAll('.brand').forEach(b=>{b.className='brand news-brand';b.href='index.html';b.innerHTML=brandMarkup();b.setAttribute('aria-label','Burlington News home')});let icon=document.querySelector('link[rel="icon"]');if(!icon){icon=document.createElement('link');icon.rel='icon';document.head.appendChild(icon)}icon.href='favicon.svg?v=20260824a'}

  function addSeo(){
    if(isHome())document.title='Burlington News | 2026 Municipal Election Guide';
    const description=document.querySelector('meta[name="description"]');if(isHome()&&description)description.content='Independent Burlington, Ontario civic news, explainers and a plain-language guide to the 2026 municipal election.';
    if(!document.querySelector('link[rel="canonical"]')){const c=document.createElement('link');c.rel='canonical';c.href=`https://electionsburlington.ca${location.pathname==='/'?'/':location.pathname}`;document.head.appendChild(c)}
    const canonical=document.querySelector('link[rel="canonical"]')?.href||location.href;
    const metas=[['og:type','website'],['og:site_name','Burlington News'],['og:locale','en_CA'],['og:title',document.title||'Burlington News'],['og:description',description?.content||'Independent Burlington, Ontario civic news and election explainers.'],['og:url',canonical],['twitter:card','summary_large_image']];
    metas.forEach(([key,value])=>{let m=document.querySelector(`meta[property="${key}"],meta[name="${key}"]`);if(!m){m=document.createElement('meta');if(key.startsWith('twitter:'))m.name=key;else m.setAttribute('property',key);document.head.appendChild(m)}m.content=value});
    document.getElementById('siteStructuredData')?.remove();const ld=document.createElement('script');ld.id='siteStructuredData';ld.type='application/ld+json';ld.textContent=JSON.stringify({'@context':'https://schema.org','@type':'WebSite',name:'Burlington News',alternateName:'Burlington Election Guide',url:'https://electionsburlington.ca/',description:'Independent Burlington, Ontario civic news, explainers and municipal election information.',inLanguage:'en-CA',about:{'@type':'Place',name:'Burlington, Ontario, Canada'}});document.head.appendChild(ld);
  }

  const icons={help:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9" fill="none" stroke="currentColor" stroke-width="1.8"/><path d="M9.8 9a2.35 2.35 0 1 1 3.3 2.15c-.75.35-1.1.8-1.1 1.6" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/><circle cx="12" cy="16.7" r="1" fill="currentColor"/></svg>',feedback:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 5.5h14v10H9l-4 3v-13Z" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linejoin="round"/><path d="M8 9h8M8 12h5" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/></svg>'};
  function buildDrawer(nav){nav.className='nav menu-panel';nav.innerHTML=`<div class="menu-panel-head"><span>Explore</span></div><div class="menu-primary" role="list"><a class="menu-link" role="listitem" href="updates.html"><span>Latest news</span><span aria-hidden="true">›</span></a><a class="menu-link" role="listitem" href="explore.html"><span>Explore Burlington</span><span aria-hidden="true">›</span></a><a class="menu-link" role="listitem" href="${homeLink('#candidates')}"><span>Meet the candidates</span><span aria-hidden="true">›</span></a><a class="menu-link" role="listitem" href="${homeLink('#matters')}"><span>Issues</span><span aria-hidden="true">›</span></a><a class="menu-link" role="listitem" href="head-to-head.html"><span>Compare candidates</span><span aria-hidden="true">›</span></a><a class="menu-link" role="listitem" href="promises.html"><span>Promises & records</span><span aria-hidden="true">›</span></a><a class="menu-link" role="listitem" href="ballot.html"><span>Your ballot</span><span aria-hidden="true">›</span></a><a class="menu-link" role="listitem" href="elections-for-beginners.html"><span>Elections for beginners</span><span aria-hidden="true">›</span></a><a class="menu-link" role="listitem" href="${homeLink('#dates')}"><span>Important dates</span><span aria-hidden="true">›</span></a><a class="menu-link" role="listitem" href="puzzles.html"><span>Puzzles</span><span aria-hidden="true">›</span></a><a class="menu-link" role="listitem" href="methodology.html"><span>Sources & methodology</span><span aria-hidden="true">›</span></a></div><div class="menu-separator" aria-hidden="true"></div><div class="menu-support" role="list"><button class="menu-support-link menu-theme-toggle" type="button" data-theme-toggle><span>Appearance</span></button><a class="menu-support-link" role="listitem" href="help.html"><span class="menu-support-icon">${icons.help}</span><span>Help</span></a><a class="menu-support-link" role="listitem" href="/feedback/"><span class="menu-support-icon">${icons.feedback}</span><span>Give feedback</span></a></div>`}
  function prepareHeader(){
    const inner=document.querySelector('.header-inner');if(!inner)return;inner.querySelector('.back')?.remove();
    let brand=inner.querySelector('.brand');if(!brand){brand=document.createElement('a');inner.prepend(brand)}brand.className='brand news-brand';brand.href='index.html';brand.innerHTML=brandMarkup();brand.setAttribute('aria-label','Burlington News home');
    let nav=document.getElementById('mainNav');if(!nav){nav=document.createElement('nav');nav.id='mainNav';nav.setAttribute('aria-label','Primary');inner.appendChild(nav)}
    let old=document.getElementById('menuBtn');if(!old){old=document.createElement('button');old.id='menuBtn';old.type='button';old.className='menu';old.setAttribute('aria-controls','mainNav');inner.appendChild(old)}
    const menu=old.cloneNode(false);menu.className='menu menu-icon-button';menu.setAttribute('aria-label','Open site menu');menu.setAttribute('aria-expanded','false');menu.innerHTML='<span class="menu-bars" aria-hidden="true"><i></i><i></i><i></i></span><span class="sr-only">Menu</span>';old.replaceWith(menu);
    let controls=inner.querySelector('.header-controls');if(!controls){controls=document.createElement('div');controls.className='header-controls';inner.insertBefore(controls,menu)}controls.appendChild(menu);buildDrawer(nav);
    nav.querySelector('[data-theme-toggle]')?.addEventListener('click',e=>{e.stopPropagation();setTheme(root.dataset.theme==='dark'?'light':'dark')});setTheme(root.dataset.theme||preferredTheme(),false);
    const close=(focus=false)=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false');document.body.classList.remove('menu-is-open');if(focus)menu.focus()};
    menu.addEventListener('click',e=>{e.stopPropagation();const open=!nav.classList.contains('open');if(open){const header=document.querySelector('.header'),banner=document.querySelector('.banner'),bottom=Math.ceil((header?.getBoundingClientRect().bottom||0));root.style.setProperty('--mobile-menu-top',`${bottom}px`);nav.classList.add('open');menu.setAttribute('aria-expanded','true');document.body.classList.add('menu-is-open');requestAnimationFrame(()=>nav.querySelector('a,button')?.focus())}else close()});nav.addEventListener('click',e=>e.stopPropagation());nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>close()));document.addEventListener('click',()=>close());document.addEventListener('keydown',e=>{if(e.key==='Escape'&&nav.classList.contains('open'))close(true)});
  }
  function installDesktopNav(){const inner=document.querySelector('.header-inner'),controls=document.querySelector('.header-controls');if(!inner||!controls||inner.querySelector('.desktop-primary-nav'))return;const nav=document.createElement('nav');nav.className='desktop-primary-nav publication-nav';nav.setAttribute('aria-label','Sections');nav.innerHTML=`<a href="updates.html">News</a><a href="explore.html">Things to do</a><a href="explore.html#free">Free</a><a href="${homeLink('#election-guide')}">Election</a><a href="puzzles.html">Games</a>`;inner.insertBefore(nav,controls)}

  function candidateData(){return[...document.querySelectorAll('#candidateStrip .candidate-card')].map((card,index)=>({card,index,name:card.querySelector('h3')?.textContent.trim()||`Candidate ${index+1}`,img:card.querySelector('img')?.src||'',initials:(card.querySelector('h3')?.textContent||'').split(/\s+/).map(x=>x[0]).join('').slice(0,2)}))}
  function buildHero(){const candidates=document.getElementById('candidates'),main=document.getElementById('main');if(!candidates||!main||document.querySelector('.election-hero'))return;document.body.classList.add('landing-home');candidates.querySelector(':scope > .eyebrow')?.remove();candidates.querySelector(':scope > .section-intro')?.remove();candidates.querySelector(':scope > .section-deck')?.remove();const old=candidates.querySelector(':scope > h1');if(old){const h=document.createElement('h2');h.textContent='Meet the candidates';old.replaceWith(h)}const people=candidateData(),hero=document.createElement('section');hero.className='election-hero';hero.setAttribute('aria-labelledby','heroTitle');hero.innerHTML=`<div class="hero-copy"><h1 id="heroTitle">Burlington's municipal election, explained.</h1><div class="hero-actions"><a class="hero-button hero-button-primary" href="head-to-head.html">Compare mayoral candidates <span aria-hidden="true">→</span></a><a class="hero-button hero-button-secondary" href="ballot.html">See your ballot</a></div><div class="hero-trust"><span>No endorsements</span><span>Independent</span></div></div><div class="hero-visual" aria-hidden="true"><div class="hero-map-card"><div class="hero-place-dot"></div><div class="hero-candidate-slide" id="heroCandidateSlide"></div><div class="hero-date-card"><span>Election day</span><strong>OCT 26</strong><small>2026</small></div><div class="hero-voting-note"><span>Voting starts</span><strong>Oct. 14</strong></div></div></div>`;main.insertBefore(hero,candidates);const slide=hero.querySelector('#heroCandidateSlide');let i=0;const paint=()=>{if(!people.length)return;const p=people[i%people.length];slide.classList.add('is-changing');setTimeout(()=>{slide.innerHTML=p.img?`<img src="${p.img}" alt=""><span>${p.name}</span>`:`<span class="hero-candidate-initials">${p.initials}</span><span>${p.name}</span>`;slide.classList.remove('is-changing')},120)};paint();if(!matchMedia('(prefers-reduced-motion: reduce)').matches&&people.length>1)setInterval(()=>{i=(i+1)%people.length;paint()},3200)}
  function setupCandidateScroll(){const strip=document.getElementById('candidateStrip');if(!strip)return;let timer=null,internal=false;const select=()=>{if(strip.scrollWidth<=strip.clientWidth+6||internal)return;const cards=[...strip.querySelectorAll('.candidate-card')],center=strip.getBoundingClientRect().left+strip.clientWidth/2;let best=cards[0],dist=Infinity;cards.forEach(c=>{const r=c.getBoundingClientRect(),d=Math.abs(r.left+r.width/2-center);if(d<dist){dist=d;best=c}});if(best&&best.getAttribute('aria-pressed')!=='true'){internal=true;best.click();setTimeout(()=>internal=false,100)}};strip.addEventListener('scroll',()=>{clearTimeout(timer);timer=setTimeout(select,90)},{passive:true});strip.querySelectorAll('.candidate-card').forEach(c=>c.addEventListener('click',()=>{if(strip.scrollWidth>strip.clientWidth+6)requestAnimationFrame(()=>c.scrollIntoView({behavior:'smooth',inline:'center',block:'nearest'}))}))}
  function ensureFooter(){let f=document.querySelector('.site-legal-footer');if(!f){f=document.createElement('footer');f.className='site-legal-footer';document.body.appendChild(f)}f.innerHTML='<div class="site-legal-footer-inner"><div class="footer-news-brand"><span class="news-brand-mark" aria-hidden="true"></span><div><strong>Burlington News</strong><p>Independent Burlington civic news and a plain-language 2026 municipal election guide.</p></div></div><nav class="site-legal-links" aria-label="Site information"><a href="elections-for-beginners.html">Elections for beginners</a><a href="puzzles.html">Puzzles</a><a href="methodology.html">Sources & methodology</a><a href="help.html#accessibility">Accessibility</a><a href="terms.html">Terms of use</a><a href="privacy.html">Privacy policy</a><a href="independent.html">Independent</a><a href="/feedback/">Give feedback</a></nav></div>'}

  setTheme(preferredTheme(),false);
  document.addEventListener('DOMContentLoaded',()=>{ensureStyles();ensureBanner();addSeo();prepareHeader();installDesktopNav();buildHero();setupCandidateScroll();ensureFooter();applyBrand();ensureScript('features-v2.js?v=20260824a','features-v2');ensureScript('news-v1.js?v=20260824a','news-v1');ensureScript('news-v2.js?v=20260824b','news-v2');setTheme(root.dataset.theme||preferredTheme(),false)});
})();
